### ISSUE TITLE
Alteração fraseologia Fulltest CRM - Cliente com Bloqueio

### ISSUE THREAD

**Issue by henmerlin** [pjefika/FulltestNode#45]
Quando a ferramenta identifica um cliente com status bloqueado, está apresentando informação como erro de cadastro:

![image.png](https://images.zenhubusercontent.com/5964e34861b4ca3b0a740009/0d88fee1-294d-4c63-a5a7-801341be5cd4);

Alterar a mensagem para: “Cliente com BLOQUEIO, por favor seguir fluxo GPS relacionado a validação de Bloqueios”

**Comment by FabioClem** [comment]
Alteração feita com sucesso, build em QA para testes.
